import Footer from "@/components/Footer";
import "./globals.css";
import Navbar from "@/components/Navbar";
export const metadata = {
  title: "TMG Competitions",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={` antialiased`}
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
